### ISSUE TITLE
gem install?

### ISSUE THREAD

**Issue by rubyFeedback** [Nakilon/rbtris#2]
Would it be possible to install rbtris via "gem install rbtris" too? I am an avid user of rubygems (gem) but I avoid bundler when possible.

**Comment by Nakilon** [comment]
I doubt it's possible with just `gem install` because ruby2d repo uses git submodules. You may try these commands though https://stackoverflow.com/a/2577404/322020

`Gemfile` and `bundle install` are supposed to do these things for you. I see no reason to avoid it.
