### ISSUE TITLE
Problem with zip

### ISSUE THREAD

**Issue by rubyFeedback** [Nakilon/rbtris#5]
uninitialized constant Zip::File (NameError)

  Zip::File.open(tempfile){ |zip| zip.extract "PressStart2P-Regular.ttf", "PressStart2P-Regular.ttf" }
     ^^^^^^

^^^ I get the above error.

Could the main .rb file perhaps be rewritten? That is an unusual error. I did install zip
but even after a gem install it still did not work.

**Comment by Nakilon** [comment]
Are you sure you launch it via `bundle exec`? There are two different zip gems in rubygems with conflicting module names.

**Comment by rubyFeedback** [comment]
I see; I thought I could just run the .rb file as-is and skipped bundle exec. So it's a user error.

Thanks for the pointer - I seem to keep on running into similar issues. :)

(As explanation: I started with ruby before bundler, so I never fully adjusted to it. I
still use the old japanese setup.rb many times, though I also use gem install when 
I have to.)

**Comment by Nakilon** [comment]
https://github.com/rubyzip/rubyzip/issues/132

> the old japanese setup.rb

I'm curious what is that.
